name = "post-purchase-upsell"
type = "checkout_post_purchase"
uid = "605817b1-8b84-d458-6e77-878311e962ab7fca9c3b"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"
